version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/app?sslmode=disable
      DIRECT_URL: postgres://postgres:postgres@db:5432/app?sslmode=disable
      ADMIN_USER: admin
      ADMIN_PASS: change-me
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  db:
