version: "3.9"
services:
  web:
    build: .
    container_name: flight-time-calculator
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      - sqlite_data:/app/prisma
    restart: unless-stopped

volumes:
  sqlite_data:
