name: Migrate DB and Deploy to Vercel

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      # Vercel project identifiers (set in repo Settings → Secrets and variables → Actions)
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      # Database URLs for Prisma migrate
      DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
      DIRECT_URL: ${{ secrets.PRODUCTION_DIRECT_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run Prisma migrations against production DB
        run: npx prisma migrate deploy

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=production --token $VERCEL_TOKEN

      - name: Build project (prebuilt artifacts)
        run: vercel build --prod --token $VERCEL_TOKEN

      - name: Deploy to Vercel (using prebuilt artifacts)
        run: vercel deploy --prebuilt --prod --token $VERCEL_TOKEN
